### ISSUE TITLE
Hello Kasper

### ISSUE THREAD

**Issue by coder789456** [kasper93/userscripts#1]
You replied to me on my issue of LAV compilation. I need your help in compiling LAV I raised my issue but Nev didn't responded me. 
I have to complete an urgent project for my college and I can even pay for this help.
hoping for a positive reply.
Thanks!

**Comment by kasper93** [comment]
Dude, stop creating new accounts and spamming random repositories. It is literally two step job. Install Visual Studio, MSYS2, unpack mingw. Add both to PATH and run build script from repository. I cannot do it for you... There is no hidden steps, you just need to run the build script.

**Comment by coder789456** [comment]
Error	LNK2001	unresolved external symbol __head_libswscale_swscale_lav_lib	LAVVideo
sir I am getting these error please guide me the reason for these errors

**Comment by coder789456** [comment]
I am trying to do this for more than 3 weeks but I am failing to do this. 
Please guide me

**Comment by kasper93** [comment]
How could I know what did you do wrong, if you just post random link error? If you really want help, you need to properly articulate what you did (all the steps and so on) and what is not working (and not in this repository...) . I will not be guessing. Like I said there is one build script that "just works". There is really not much to explain.

0. Install Visual Studio, MSYS2, unpack mingw. Add both to PATH.
1. Run build.bat https://github.com/Nevcairiel/LAVFilters/blob/master/build.bat

And it will build.
